name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 'v3.0.0-preview3'
    - name: Run a multi-line script
      run: |
        bash build.sh
