name: Volte CI

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100-preview3-010431'
    - name: build the damn thing
      run: bash build.sh
